## Matrix-Vector Products

Example:
Current health states of AIDS:

- 85% asymptomatic
- 10% symptomatic
- 5% aids
- 0% death

The following matrix gives the probabilities of moving from one health state to another in a year.
$$\left[\begin{array}{cccc}
0.90 & 0.07 & 0.02 & 0.01	\\
0 & 0.93 & 0.05 & 0.02	\\
0 & 0 & 0.85 & 0.15	\\
0 & 0 & 0 & 1.00
\end{array}\right]$$


This matrix corresponds to:
![Markov Health](images/markov_health.jpg)

In [1]:
import numpy as np

In [3]:
# now we'll find the % in each health state in one year.

stochastic_matrix = np.matrix([[0.90,0.07,0.02,0.01],[0,0.93,0.05,0.02],[0,0,0.85,0.15],[0,0,0,1.00]])
curr_health = np.array([0.85,0.10,0.05,0])

In [6]:
curr_health.T.shape

(4,)

Recall that * is for element-wise mult, so we must use np.dot.

In [19]:
new_states = curr_health.T * stochastic_matrix

In [11]:
curr_health.T

array([ 0.85,  0.1 ,  0.05,  0.  ])

In [15]:
stochastic_matrix

matrix([[ 0.9 ,  0.07,  0.02,  0.01],
        [ 0.  ,  0.93,  0.05,  0.02],
        [ 0.  ,  0.  ,  0.85,  0.15],
        [ 0.  ,  0.  ,  0.  ,  1.  ]])

In [20]:
new_states

matrix([[ 0.765 ,  0.1525,  0.0645,  0.018 ]])

Let's also try it this way:

In [22]:
print(stochastic_matrix.dot(curr_health))

[[ 0.773   0.0955  0.0425  0.    ]]


It's different.

## Matrix-Matrix

![Example](images/shop.png)

In [23]:
dem_quant = np.matrix([[6,5,3,1],[3,6,2,2],[3,4,3,1]])
shop_prices = np.matrix([[1.50,1.00],[2.00,2.50],
                         [5.00,4.50],[16.00,17.00]])

In [24]:
best_shops = dem_quant*shop_prices

In [25]:
best_shops

matrix([[ 50. ,  49. ],
        [ 58.5,  61. ],
        [ 43.5,  43.5]])

The above represents, based on the demand quantities, which is the better shop for each person. First row is for $P_1$, f or whom shop $2$ is better since they spend only $49.

### Image

![Image Data](images/digit.gif)

### Convolutions

![Predict Sports](images/sportspredict.jpeg)

Recall how a convolution works:

![convolution](images/cnn1.png)

NN viewpoint:
![NN](images/cnn2.png)

Matrix mult:
![matrix](images/cnn3.png)

## Notes

IEEE Double precision arithmetic:

Numbers can be as large as $1.79 \times 10^{308}$ and as small as $2.23 \times 10^{-308}$.
The interval $[1,2]$ is represented by discrete subset: $$1, \: 1+2^{-52}, \: 1+2 \times 2^{-52},\: 1+3 \times 2^{-52},\: \ldots, 2$$

The interval $[2,4]$ is represented: $$2, \: 2+2^{-51}, \: 2+2 \times 2^{-51},\: 2+3 \times 2^{-51},\: \ldots, 4$$

Floats and doubles are not equidistant:


Machine Epsilon

Half the distance between 1 and the next larger number. This can vary by computer. IEEE standards for double precision specify $$ \varepsilon_{machine} = 2^{-53} \approx 1.11 \times 10^{-16}$$

Two important properties of Floating Point Arithmetic:

The difference between a real number $x$ and its closest floating point approximation $fl(x)$ is always smaller than $\varepsilon_{machine}$ in relative terms. For some $\varepsilon$, where $\lvert \varepsilon \rvert \leq \varepsilon_{machine}$, $$fl(x)=x \cdot (1 + \varepsilon)$$

Where is any operation ($+, -, \times, \div$), and $\circledast$ is its floating point analogue, $$ x \circledast y = (x </em> y)(1 + \varepsilon)$$ for some $\varepsilon$, where $\lvert \varepsilon \rvert \leq \varepsilon <em>{machine}$ That is, every operation of floating point arithmetic is exact up to a relative error of size at most $\varepsilon</em>{machine}$